// Generated by Supabase (`generate_typescript_types`). Regenerate after any
// schema change; do not hand-edit. Captures the loop-review project's public
// schema so the server-side Supabase client is fully typed.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      ai_insights: {
        Row: {
          created_by: string | null
          data: Json
          generated_at: string
          id: string
          model: string | null
          tenant_id: string
          window_days: number
        }
        Insert: {
          created_by?: string | null
          data: Json
          generated_at?: string
          id?: string
          model?: string | null
          tenant_id: string
          window_days?: number
        }
        Update: {
          created_by?: string | null
          data?: Json
          generated_at?: string
          id?: string
          model?: string | null
          tenant_id?: string
          window_days?: number
        }
        Relationships: [
          {
            foreignKeyName: "ai_insights_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      notifications: {
        Row: {
          channel: string
          created_at: string
          destination: string | null
          error: string | null
          id: string
          sent_at: string | null
          status: string
          submission_id: string
        }
        Insert: {
          channel: string
          created_at?: string
          destination?: string | null
          error?: string | null
          id?: string
          sent_at?: string | null
          status?: string
          submission_id: string
        }
        Update: {
          channel?: string
          created_at?: string
          destination?: string | null
          error?: string | null
          id?: string
          sent_at?: string | null
          status?: string
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      submission_notes: {
        Row: {
          author_id: string
          body: string
          created_at: string
          id: string
          submission_id: string
          tenant_id: string
        }
        Insert: {
          author_id?: string
          body: string
          created_at?: string
          id?: string
          submission_id: string
          tenant_id: string
        }
        Update: {
          author_id?: string
          body?: string
          created_at?: string
          id?: string
          submission_id?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "submission_notes_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submission_notes_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      submissions: {
        Row: {
          created_at: string
          id: string
          ip_hash: string | null
          kind: string
          language: string
          message: string
          priority: string
          rating: number | null
          resolved: boolean
          resolved_at: string | null
          session_id: string
          table_id: string | null
          tag_keys: string[]
          tenant_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          ip_hash?: string | null
          kind: string
          language: string
          message?: string
          priority: string
          rating?: number | null
          resolved?: boolean
          resolved_at?: string | null
          session_id: string
          table_id?: string | null
          tag_keys?: string[]
          tenant_id: string
        }
        Update: {
          created_at?: string
          id?: string
          ip_hash?: string | null
          kind?: string
          language?: string
          message?: string
          priority?: string
          rating?: number | null
          resolved?: boolean
          resolved_at?: string | null
          session_id?: string
          table_id?: string | null
          tag_keys?: string[]
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "submissions_table_id_fkey"
            columns: ["table_id"]
            isOneToOne: false
            referencedRelation: "tables"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tables: {
        Row: {
          active: boolean
          created_at: string
          id: string
          label: string
          server_name: string | null
          tenant_id: string
          token: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          id?: string
          label: string
          server_name?: string | null
          tenant_id: string
          token?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          id?: string
          label?: string
          server_name?: string | null
          tenant_id?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "tables_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_invites: {
        Row: {
          created_at: string
          email: string
          id: string
          role: string
          tenant_id: string
        }
        Insert: {
          created_at?: string
          email: string
          id?: string
          role: string
          tenant_id: string
        }
        Update: {
          created_at?: string
          email?: string
          id?: string
          role?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_invites_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_members: {
        Row: {
          created_at: string
          role: string
          tenant_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          role?: string
          tenant_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          role?: string
          tenant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_members_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_notification_channels: {
        Row: {
          created_at: string
          destination: string
          enabled: boolean
          id: string
          kind: string
          label: string | null
          tenant_id: string
        }
        Insert: {
          created_at?: string
          destination: string
          enabled?: boolean
          id?: string
          kind: string
          label?: string | null
          tenant_id: string
        }
        Update: {
          created_at?: string
          destination?: string
          enabled?: boolean
          id?: string
          kind?: string
          label?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_notification_channels_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_platforms: {
        Row: {
          created_at: string
          enabled: boolean
          id: string
          kind: string
          label: string
          sort_order: number
          tenant_id: string
          url: string
        }
        Insert: {
          created_at?: string
          enabled?: boolean
          id?: string
          kind: string
          label: string
          sort_order?: number
          tenant_id: string
          url: string
        }
        Update: {
          created_at?: string
          enabled?: boolean
          id?: string
          kind?: string
          label?: string
          sort_order?: number
          tenant_id?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_platforms_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          brand_color: string | null
          created_at: string
          google_review_url: string | null
          id: string
          location_name: string
          logo_url: string | null
          manager_email: string | null
          manager_name: string | null
          name: string
          public_review_min_rating: number
          show_name_with_logo: boolean
          slug: string
          tagline: string | null
          tripadvisor_review_url: string | null
        }
        Insert: {
          brand_color?: string | null
          created_at?: string
          google_review_url?: string | null
          id?: string
          location_name: string
          logo_url?: string | null
          manager_email?: string | null
          manager_name?: string | null
          name: string
          public_review_min_rating?: number
          show_name_with_logo?: boolean
          slug: string
          tagline?: string | null
          tripadvisor_review_url?: string | null
        }
        Update: {
          brand_color?: string | null
          created_at?: string
          google_review_url?: string | null
          id?: string
          location_name?: string
          logo_url?: string | null
          manager_email?: string | null
          manager_name?: string | null
          name?: string
          public_review_min_rating?: number
          show_name_with_logo?: boolean
          slug?: string
          tagline?: string | null
          tripadvisor_review_url?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      add_team_member: {
        Args: { p_email: string; p_role: string; p_tenant_id: string }
        Returns: string
      }
      current_manager_tenant_ids: { Args: never; Returns: string[] }
      current_owner_tenant_ids: { Args: never; Returns: string[] }
      current_tenant_ids: { Args: never; Returns: string[] }
      get_card: {
        Args: { p_slug: string }
        Returns: {
          brand_color: string
          brand_name: string
          location_name: string
          logo_url: string
          platforms: Json
          tagline: string
        }[]
      }
      get_home_venue: {
        Args: never
        Returns: {
          brand_color: string
          brand_name: string
          location_name: string
          logo_url: string
          platforms: Json
          public_review_min_rating: number
          show_name_with_logo: boolean
          tagline: string
        }[]
      }
      get_venue: {
        Args: { p_slug: string; p_table_label: string; p_token: string }
        Returns: {
          brand_color: string
          brand_name: string
          location_name: string
          logo_url: string
          platforms: Json
          public_review_min_rating: number
          server_name: string
          show_name_with_logo: boolean
          tagline: string
        }[]
      }
      list_team_members: {
        Args: { p_tenant_id: string }
        Returns: {
          email: string
          role: string
          user_id: string
        }[]
      }
      purge_old_feedback: { Args: never; Returns: undefined }
      remove_team_member: {
        Args: { p_tenant_id: string; p_user_id: string }
        Returns: undefined
      }
      rotate_table_token: { Args: { p_table_id: string }; Returns: string }
      set_team_role: {
        Args: { p_role: string; p_tenant_id: string; p_user_id: string }
        Returns: undefined
      }
      submit_review: {
        Args: {
          p_ip_hash: string
          p_kind: string
          p_language: string
          p_message: string
          p_rating: number
          p_session_id: string
          p_slug: string
          p_table_label: string
          p_tag_keys: string[]
          p_token: string
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
