// Generated by Supabase (`generate_typescript_types`). Regenerate after any
// schema change; do not hand-edit. Captures the loop-review project's public
// schema so the server-side Supabase client is fully typed.
export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      notifications: {
        Row: {
          channel: string
          created_at: string
          destination: string | null
          error: string | null
          id: string
          sent_at: string | null
          status: string
          submission_id: string
        }
        Insert: {
          channel: string
          created_at?: string
          destination?: string | null
          error?: string | null
          id?: string
          sent_at?: string | null
          status?: string
          submission_id: string
        }
        Update: {
          channel?: string
          created_at?: string
          destination?: string | null
          error?: string | null
          id?: string
          sent_at?: string | null
          status?: string
          submission_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "notifications_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_notification_channels: {
        Row: {
          created_at: string
          destination: string
          enabled: boolean
          id: string
          kind: string
          label: string | null
          tenant_id: string
        }
        Insert: {
          created_at?: string
          destination: string
          enabled?: boolean
          id?: string
          kind: string
          label?: string | null
          tenant_id: string
        }
        Update: {
          created_at?: string
          destination?: string
          enabled?: boolean
          id?: string
          kind?: string
          label?: string | null
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_notification_channels_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      submissions: {
        Row: {
          created_at: string
          id: string
          ip_hash: string | null
          kind: string
          language: string
          message: string
          priority: string
          rating: number | null
          resolved: boolean
          resolved_at: string | null
          session_id: string
          table_id: string | null
          tag_keys: string[]
          tenant_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          ip_hash?: string | null
          kind: string
          language: string
          message?: string
          priority: string
          rating?: number | null
          resolved?: boolean
          resolved_at?: string | null
          session_id: string
          table_id?: string | null
          tag_keys?: string[]
          tenant_id: string
        }
        Update: {
          created_at?: string
          id?: string
          ip_hash?: string | null
          kind?: string
          language?: string
          message?: string
          priority?: string
          rating?: number | null
          resolved?: boolean
          resolved_at?: string | null
          session_id?: string
          table_id?: string | null
          tag_keys?: string[]
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "submissions_table_id_fkey"
            columns: ["table_id"]
            isOneToOne: false
            referencedRelation: "tables"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "submissions_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      submission_notes: {
        Row: {
          author_id: string
          body: string
          created_at: string
          id: string
          submission_id: string
          tenant_id: string
        }
        Insert: {
          author_id?: string
          body: string
          created_at?: string
          id?: string
          submission_id: string
          tenant_id: string
        }
        Update: {
          author_id?: string
          body?: string
          created_at?: string
          id?: string
          submission_id?: string
          tenant_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "submission_notes_submission_id_fkey"
            columns: ["submission_id"]
            isOneToOne: false
            referencedRelation: "submissions"
            referencedColumns: ["id"]
          },
        ]
      }
      tables: {
        Row: {
          active: boolean
          created_at: string
          id: string
          label: string
          server_name: string | null
          tenant_id: string
          token: string
        }
        Insert: {
          active?: boolean
          created_at?: string
          id?: string
          label: string
          server_name?: string | null
          tenant_id: string
          token?: string
        }
        Update: {
          active?: boolean
          created_at?: string
          id?: string
          label?: string
          server_name?: string | null
          tenant_id?: string
          token?: string
        }
        Relationships: [
          {
            foreignKeyName: "tables_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_members: {
        Row: {
          created_at: string
          role: string
          tenant_id: string
          user_id: string
        }
        Insert: {
          created_at?: string
          role?: string
          tenant_id: string
          user_id: string
        }
        Update: {
          created_at?: string
          role?: string
          tenant_id?: string
          user_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_members_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenant_platforms: {
        Row: {
          created_at: string
          enabled: boolean
          id: string
          kind: string
          label: string
          sort_order: number
          tenant_id: string
          url: string
        }
        Insert: {
          created_at?: string
          enabled?: boolean
          id?: string
          kind: string
          label: string
          sort_order?: number
          tenant_id: string
          url: string
        }
        Update: {
          created_at?: string
          enabled?: boolean
          id?: string
          kind?: string
          label?: string
          sort_order?: number
          tenant_id?: string
          url?: string
        }
        Relationships: [
          {
            foreignKeyName: "tenant_platforms_tenant_id_fkey"
            columns: ["tenant_id"]
            isOneToOne: false
            referencedRelation: "tenants"
            referencedColumns: ["id"]
          },
        ]
      }
      tenants: {
        Row: {
          brand_color: string | null
          created_at: string
          google_review_url: string | null
          id: string
          location_name: string
          logo_url: string | null
          manager_email: string | null
          manager_name: string | null
          name: string
          slug: string
          tagline: string | null
          tripadvisor_review_url: string | null
        }
        Insert: {
          created_at?: string
          google_review_url?: string | null
          id?: string
          location_name: string
          manager_email?: string | null
          manager_name?: string | null
          name: string
          slug: string
          tagline?: string | null
          tripadvisor_review_url?: string | null
        }
        Update: {
          created_at?: string
          google_review_url?: string | null
          id?: string
          location_name?: string
          manager_email?: string | null
          manager_name?: string | null
          name?: string
          slug?: string
          tagline?: string | null
          tripadvisor_review_url?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      current_tenant_ids: {
        Args: Record<string, never>
        Returns: string[]
      }
      get_venue: {
        Args: {
          p_slug: string
          p_table_label: string
          p_token: string
        }
        Returns: {
          brand_name: string
          tagline: string
          location_name: string
          logo_url: string
          brand_color: string
          server_name: string
          platforms: Json
        }[]
      }
      submit_review: {
        Args: {
          p_ip_hash: string
          p_kind: string
          p_language: string
          p_message: string
          p_rating: number
          p_session_id: string
          p_slug: string
          p_table_label: string
          p_tag_keys: string[]
          p_token: string
        }
        Returns: string
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}
